[
build
]
  publish = "."
  command = "echo 'Déploiement du site UL'"

[[
headers
]]
  for = "/*"
  [
headers.values
]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdnjs.cloudflare.com; style-src 'self' https://fonts.googleapis.com"

[
context.production.environment
]
  RUBY_VERSION = "3.1.2"

[[
redirects
]]
  from = "/*"
  to = "/index.html"
  status = 200